name: Deploy Node.js app to DigitalOcean

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    env:
      HOST: ${{ secrets.HOST }}
      USER: ${{ secrets.USER }}
      PORT: ${{ secrets.PORT }}
      SECRET_KEY: ${{ secrets.SECRET_KEY }}
      MONGO_URI: ${{ secrets.MONGO_URI }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Deploy with rsync
        uses: appleboy/rsync-action@v1.0.1
        with:
          host: ${{ secrets.Priyanka_HOST }}
          username: ${{ secrets.Priyanka_USER }}
          port: ${{ secrets.Priyanka_PORT }}
          source: "."
          target: "/home/node-app"
          rm: true
          ssh_key: ${{ secrets.Priyanka_SSH_KEY }}

      - name: Deploy with ssh
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.Priyanka_HOST }}
          username: ${{ secrets.Priyanka_USER }}
          port: ${{ secrets.Priyanka_PORT }}
          script: |
            cd /root/nodejs-app-deploy-github-actions
            git pull
            docker compose up -d --build

          #  cd /home/node-app
          #   docker compose -f docker-compose.yml down && docker compose -f docker-compose.yml up -d --build
          ssh_key: ${{ secrets.Priyanka_SSH_KEY }}
